/**
 * Alipay.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */
package org.zyq.leetcode.no389;

import static org.zyq.leetcode.util.LeetUtil.output;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * @author yuqing.zyq
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int result = 0;
        for (char c : s.toCharArray()) {
            result -= c;
        }
        for (char c : t.toCharArray()) {
            result += c;
        }

        return (char) result;
    }

    public char findTheDifference_2(String s, String t) {
        int result = 0;
        for (char c : s.toCharArray()) {
            result ^= c;
        }
        for (char c : t.toCharArray()) {
            result ^= c;
        }

        return (char) result;
    }

    public static void main(String[] args) {
        FindTheDifference ftd = new FindTheDifference();
        String s = "abcd";
        String t = "adcbe";
        output(s, t, ftd.findTheDifference_2(s, t));

        s = "abcde";
        t = "edcbas";
        output(s, t, ftd.findTheDifference_2(s, t));
    }
}
